lib/inlines.js

The other return statements also return a boolean.

Return false instead of 0 from parseBackticks

---

lib/blocks.js

By the time parseListMarker is called, the hrule block start was already
tried. In case it matches, no further block starts are tried. So the
later check is not necessary and can be removed.

Remove unnecessary check for hrule in parseListMarker

---

lib/inlines.js

This seems to yield a speed boost of about 5-10 % using `make bench`. I'd be interested if you can reproduce the results :).

Optimize checking for final spaces in parseNewline

---

README.md

Just a quick typo fix in README.md

Typographical error fix, "THe" -> "The"

---

lib/inlines.js

Also, abort earlier when no delims where found.
Couldn't determine a measurable performance impact, but code feels nicer that way.

Extract RE test results in scanDelims as local variables

---

lib/xml.js

Image nodes in a CommonMark AST are containers, and as such the XML writer will always output a closing tag.
Clicking "AST" in [this dingus](http://spec.commonmark.org/dingus/?text=!%5B%5D(http%3A%2F%2Fexample.org)) shows the problem:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CommonMark SYSTEM "CommonMark.dtd">
<document sourcepos="1:1-1:23">
<paragraph sourcepos="1:1-1:23">
<image destination="http://example.org" title="" />
</image>
</paragraph>
</document>
The image tag is both self-closing (`/>`) and has a closing `</image>` tag.
Side note: I ran `make lint` as per [CONTRIBUTING](https://github.com/jgm/commonmark.js/blob/master/CONTRIBUTING.md), and there is indeed one error in `xml.js`. I did not fix it because it is unrelated to this change.

Don't consider images to be self-closing in the XML writer.

---

lib/inlines.js

Per 6.1,
> Backslashes before other characters are treated as literal backslashes
The definition of a link destination does not preclude such backslashes from appearing (and in fact it already works if the link is inside angle brackets).
[Dingus link of the cases this fixes](http://spec.commonmark.org/dingus/?text=%5Bfoo%5D(%5Cx)%0A%0A%5Bfoo%5D((%5Cx))%0A%0A%5Bfoo%5D%5B1%5D%0A%0A%5Bfoo%5D%5B2%5D%0A%0A%5B1%5D%3A%20%5Cx%0A%5B2%5D%3A%20(%5Cx)%0A) (all four should be links).
This probably warrants a test, but I'm not sure whether you want such cases as examples in the spec or in a different place.
As far as I can tell from looking at [the code](https://github.com/jgm/cmark/blob/1acd161b2f25e71a40c903ea8997a6ee2f4694d2/src/scanners.re), cmark requires the same change; unfortunately I don't …

Allow literal (non-escaping) backslashes in link destinations

---

lib/inlines.js

If the reference seems to have a valid title that however does not go until the end of the line, check if the reference becomes valid when discarding the title.
[Dingus link](http://spec.commonmark.org/dingus/?text=%5Bfoo%5D%3A%20%2Furl%0A%22title%22%20ok); source:
```markdown
[foo]: /url
"title" ok
```
Expected output:
```html
<p>&quot;title&quot; ok</p>
```
Actual output:
```html
<p>[foo]: /url
&quot;title&quot; ok</p>
```

Fix link reference definition edge case.

---

lib/inlines.js
package.json
test/smart_punct.txt

- Adds tests for longer sequences of hyphens
- Changes behavior as follows:
```
Current: ---------- => --- --- --- -  => ———-
New: ---------- => -- -- -- -- -- => –––––
Current: ------- => --- --- - => ——-
New: ------- => --- -- -- => —––
Current: ---- => --- - => —-
New: ---- => -- -- => ––
```

Switch to "smart" hyphen replacement (closes #56)

---

lib/inlines.js
test/smart_punct.txt

```
'We'll use Jane's boat and John's truck,' Jenna said.
```
...currently outputs backwards apostrophes in cases with multiple apostrophes per paragraph:
```
<p>‘We‘ll use Jane‘s boat and John‘s truck,’ Jenna said.</p>
```
This fix makes changes the output to:
```
<p>‘We’ll use Jane’s boat and John’s truck,’ Jenna said.</p>
```
A little hard to tell on GitHub, but if you change the font to one that differentiates quotes more, you'll be able to tell.

Fix replacement of multiple apostrophes in the same paragraph.

---

.travis.yml

Remove testing on iojs, since it has been merged back in with node.js

Test on node.js 5.x and 4.x

---

lib/blocks.js

I don't know if this is there for a reason, but `markerStartCol` isn't being used anywhere
and can be removed.
It was introduced just recently in commit 3ffa89306c1be42fe3a6071b4007b1dbca82505c

Remove unused variable markerStartCol

---

lib/render/html.js

Tiny change, tests passing. Likely won't affect performance although it does prevent a call to the `Renderer` constructor when assigning to `prototype`.
I don't know what your browser targets are but this should be fine with all modern browsers (IE9+).

Better ECMAScript 5 style inheritance.

---

.npmignore

Otherwise installing with `npm i jgm/commonmark.js` does not include the `render` directory that was recently merged.

Ensure render directory is installed by npm.

---

lib/blocks.js

It looks like `columns` is always true in this block, so there's no need to check it during the assignment to `count`.

remove unnecessary check

---

lib/inlines.js

The key insight for the simplification is that we don't need to keep the
brackets in the same stack as the other delimiters. All we need to know
is which delimiter came before the bracket, so that we can process the
emphasis in the image/link text.
This removes the need to loop to find the last opening bracket and also
removes the need to skip over brackets in processEmphasis.
In addition to that, we can skip the slice and reference lookup for
collapsed/shortcut reference links if we know that it contains a
bracket.
Together, these changes make the "nested brackets 10000 deep"
pathological case go from 400 ms to 20 ms.
Before:
> nested brackets 1000 deep ✓
>   elapsed time: 6.342ms
> nested brackets 10000 deep ✓
>   elapsed time: 402.198ms
After:
> nested brackets 1000 deep ✓
>   elapsed …

Simplify and optimize brackets processing (links/images)

---

lib/blocks.js

I found probably a copy-paste error. 
`this.count` on `Parser` object is used only in one place. I think argument `count` was meant.
This doesn't affect test results, but could lead to potential problems in future.

Fix not existing property usage.

---

lib/blocks.js

Variable `cols` is used for incrementing, but the result is never used.

Remove unused write-only variable.

---

lib/inlines.js

The spec makes an distinction between "[whitespace]" and "[Unicode whitespace]": whereas the latter include many additional whitespace characters, particularly the non-breaking space (U+00A0), the former does not.
Per ECMA-262 6th Edition ("ECMAScript 2015") §21.2.2.12 [CharacterClassEscape], the JavaScript `\s` escape character matches the characters specified by "Unicode whitespace," but not "whitespace."
To fix this issue, rename the existing regular expression variable to `UnicodeWhitespace`, and create and use a new regular expression variable that only matches the limited set of "whitespace" characters.
The test suite does not yet cover this distinction. I will add a corresponding test case when this pull request has been accepted.
For additional information, the distinction in the …

Make an distinction between Unicode whitespace and regular whitespace

---

lib/index.js
lib/render/xml.js

This is a draft port of the existing xml renderer. It appears that the xml renderer does not feature in any of the tests so I tested this code with:
```
./bin/commonmark -t xml README.md > original.txt
./bin/commonmark -t xml README.md > ported.txt
diff original.txt ported.txt
```
Switching the renderers used in between generating the files.
If we are confident that this is functioning as expected and are happy to merge this than we can remove the older renderers in the `lib` directory.

Initial xml renderer migration.

---

.npmignore
Makefile
README.md
bench/bench.js
dingus/Makefile
package-lock.json
package.json

Packages used during development are now listed in devDependencies of
package.json. Makefiles are updated to use those local versions.
References to manually installing packages are removed from README.md
and bench/bench.js. The package-lock.json file used in newer NPM
versions is also added.
Fixes: #142

Use local development dependencies

---

lib/inlines.js

`ESCAPED_CHAR` already matches `\\`, so matching it again in another alternative was just causing an exponential complexity explosion.
Fixes #157.

Fix two exponential regex backtracking vulnerabilities

---

dingus/.gitignore
dingus/bower.json

Dingus was rendering incorrectly with Bootstrap 4. Added a bower.json
which requires Bootstrap, jQuery and Lodash with major version equal
to what's currently live. Likewise the minimum patch version.

dingus: add dependency version requirements

---

lib/index.js

This will allow consumers to extend from this class to create their own custom renderers, so they can export to any other format besides HTML and XML, such as JSON, Markdown (for transformations/linters), etc.

Export `Renderer` constructor function

---

bin/commonmark

If you run this:
```
./commonmark.js 1
```
Minimist converts 1 to a number, then fs.readFileSync(1, 'utf8') will
actually read FD 1 (i.e. stdin) instead of a file as one would expect.
Related issues:
https://github.com/substack/minimist/issues/36
https://github.com/substack/minimist/issues/32

Avoid numerical conversion for file names in argv

---

lib/render/html.js

The argument was removed from the function definition itself in commit
562b8671d1b12b159562f71ea5939ce3c45a0cff.

Remove no longer used argument to escapeXml

---

.editorconfig

All of the JS source uses an indent of 4, but the .editorconfig has it as 2.

Sync .editorconfig indent_size to actual

---

lib/common.js
test/regression.txt

Decoding before encoding leads to invalid urls. Here's an example:
Let's assume this markdown:
```md
[link](https://www.example.com/home/%25batty)
```
> Note: `%25` is the code for the `%` character
This results in:
```
var dest1 = decode("https://www.example.com/home/%25batty")
//dest1 = https://www.example.com/home/%batty
var dest2 = encode(dest1)
// dest2 = https://www.example.com/home/%batty 
```
since `%ba` is a potential percentage-encoded hex code, mdurl's encode doesn't change it. resulting in an invalid link.
As far as I'm aware, just doing `encode(uri)` is doing the desired thing. for all kinds of uris

Don't decode url before encoding it again

---

lib/blocks.js

A totally innocuous mistake discovered by my IDE.

Remove redundant token from reHtmlBlockOpen

---

package.json

Removed space chars that were resulting in invalid dependency declarations, which were masked by the fact that Markdown-it's package.json happened to install these dependencies correctly.
`npm ls` will confirm the problem, and will confirm it's gone after applying the patch.

Fixed invalid package.json dependency entries.

---

lib/inlines.js

A clause in the condition gating whether to add a parsed
`'` or `"` to the delimiter stack *always* evaluated to TRUE.
What is clearly a typo happened to not break any tests
and *probably* only wasted a bit of memory and CPU.
This commit reflects what I believe to be the original
intention: Only add `'` and `"` if smart quotes is enabled.

Remove superfluous push to delimiter stack in handleDelim

---

bin/commonmark

On Linux, the shebang feeds the parameters to the command (here, env) as a single parameter string.
Thus, running this script on Linux yielded an error:
> env: ‘node -r esm’: No such file or directory
> env: use -[v]S to pass options in shebang lines
Using -S tells env to split the string it receives and feed the parameters to the program it forks.

Use env -S to split the parameter string

---

.github/workflows/ci.yml

This tiny PR changes the GitHub Actions configuration for continuous integration to test on Node.js version 14.x, which is the latest long-term-support major version, and version 15.x, the "current" major version.

Configure GitHub Actions to test on Node.js 14 and 15

---

lib/index.js

This small PR updates the "Basic Usage" example in a comment in `lib/index.js` to correctly reflect how to `import` from an ES Module.
Note that as converted to ES Modules, `commonmark` does _not_ export anything by default.  Users needs to do `import { Parser, HtmlRendered} from 'commonmark'` or the like, or alternatively `import * as commonmark from 'commonmark'`. Plain old `import commonmark from 'commonmark'` won't work.
This PR does _not_ fix errors loading the package under Node.js.  More on that shortly.

Update "Basic Usage" comment in lib/index.js

---

Makefile
bench/package.json
bin/commonmark
dist/package.json
lib/common.js
lib/inlines.js
lib/package.json
package-lock.json
package.json
test/package.json

This PR attempts to resolve various issues and errors affecting bin script execution and loading via `import` in Node.js. It doesn't touch the existing conditional-import or `module` bunlder entry point configurations in `package.json` at root.
Overall, the blunt instrument at work here is `package.json` files with `"type":"module"` set. In order to make clear to Node.js what is an old CommonJS module and what is a new ES Module, we have just a few choices:
- Use `.cjs` for CommonJS and `.mjs` for ES Modules. But old versions of Node don't know about this convention.
- Pass flags to Node. But again, only recent versions of Node know the latest flags. And we generally don't control how Node.js is invoked, outside our own tests and other development scripts.
- Set `type` to `"commonjs"` or …

Cure ES Module Madness

---

bench/bench.js
bench/package.json
package-lock.json
test/package.json
test/test.js

This PR reverts work porting test and benchmark scripts to ES Modules.
Until we're ready to drop support for Node.js versions with ES Module support, we need to keep the test and benchmark runners in CommonJS, so the old Node.js versions we want to test on can run them.

CommonJS Tests and Benchmarks Again

---

README.md

The parser produces lowercase strings, but the README said the strings are capitalized.

Fix documentation for `node.listType`

---

dingus/dingus.js

To quote https://stackoverflow.com/a/36155560/438544:
> Using .load() isn't possible if the iframe has already been loaded (event will never fire)
Closes commonmark/commonmark-spec-web#15.

Fixes an iframe loading timing issue

---

README.md
lib/render/html.js
lib/render/xml.js

README.md says you can specify an `esc` function to customise escaping of the output.
However, this isn't the case. Your `esc` function argument is roundly ignored. I've changed this in the `XML` and `HTML` parsers so it's now taken into account.
The docs used to say the `esc` function takes two parameters, the string and whether it should be escaped, but this is not the case in the codebase, so I've changed the README.md

Allow user to specify a function to escape the output

---

lib/inlines.js

[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.

Replace deprecated String.prototype.substr()

---

lib/inlines.js
test/regression.txt

Fixes #271
The reasoning that a failed delimiter means future delimiters will also fail only applies if the reason they failed was not the multiple-of-three rule. This was already implemented correctly for asterisks, but not for underscore.

Track underscore bottom separately mod 3, like asterisk

---

lib/inlines.js
package.json

Every browser supports `string.prototype.repeat` since 2016 so the polyfill can be removed now.
https://caniuse.com/mdn-javascript_builtins_string_repeat
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/repeat

Remove `string.prototype.repeat` polyfill

---

lib/inlines.js

The regex introduced in #289 can be slow.
For example,
```js
('a' + ' '.repeat(65534) + 'a').replace(/^[\t \r\n]+|[\t \r\n]+$/g,"").length
```
takes a long time to be done. (a few seconds)
```js
/^[\t \r\n]+(?![\t \r\n])|(?<![\t \r\n])[\t \r\n]+$/g,
```
fixes the problem, but the naive implementation of this PR seems to be faster than it when the number of trimmed spaces are not many according to my private bench by [mitata](https://github.com/evanwashere/mitata).
Using `charCodeAt` is fastest but reduces the explainability due to the raw code point number literals (e.g. 0x20 for " ").
Sorry for having submitted problematic code.
```js
import { run, bench, boxplot } from "mitata";
const PAD = " \n".repeat(16777216)
const PAD2 = " \n\t".repeat(1024)
const CH = "abc".repeat(16777216)
const …
```

Don't use regex that can be slow
